FROM node:17-alpine AS builder

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY prisma/ .
COPY .env .

RUN npm install

COPY . .

FROM node:17-alpine as app

WORKDIR /app

COPY --from=builder /app/package.json .
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/src src
COPY --from=builder /app/prisma prisma
COPY --from=builder /app/.env .env

EXPOSE 8000

ENTRYPOINT ["npm", "run"]

CMD ["start:migrate:prod"]